import Head from 'next/head'

export default function Home() {
  const bgImageStyle = {
    backgroundImage: 'url(/images/banner.jpg)',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    backgroundRepeat: 'no-repeat'
  }

  return (
    <>
      <Head>
        <title>RSPro.es</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className="flex flex-col items-center w-4/5 ml-auto">
        <header style={bgImageStyle} className="flex justify-center items-end w-full h-3/5">
          <div className="flex flex-col justify-center gap-3 items-center text-white pb-16">
            <h1 className="font-semibold font-lato text-2xl">
              Proyectos de Responsabilidad Social Profesional
            </h1>

            <span className="italic">
              RSPro: Explore sus capacidades más allá de lo profesional
            </span>
          </div>
        </header>

        <article className="px-16 py-8">
          <h2 className="text-2xl text-customRed font-semibold">
            RSPro: Experimentar con responsabilidad
          </h2>
        </article>
      </section>
    </>
  )
}

